# Generated by Django 3.2.14 on 2022-08-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questioninputchoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questioninputchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='responseinstance',
            name='question',
        ),
        migrations.RemoveField(
            model_name='responseinstance',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='screeningtool',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='screeningtool',
            name='questionnaire',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionInputChoice',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.DeleteModel(
            name='QuestionnaireResponse',
        ),
        migrations.DeleteModel(
            name='ResponseInstance',
        ),
        migrations.DeleteModel(
            name='ScreeningTool',
        ),
    ]
