# Generated by Django 3.2.14 on 2022-08-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='has_expiry',
            field=models.BooleanField(default=False),
        ),
    ]
