# Generated by Django 3.2.14 on 2022-08-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questioninputchoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questioninputchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='responseinstance',
            name='question',
        ),
        migrations.RemoveField(
            model_name='responseinstance',
            name='questionnaire',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionInputChoice',
        ),
        migrations.DeleteModel(
            name='ResponseInstance',
        ),
    ]
