apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
     app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        team: ""
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.app.container.image }}
          imagePullPolicy: {{ .Values.app.container.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.container.port }}
              protocol: TCP
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: {{ .Values.app.container.env.googleCloudProject | quote }}
            - name: SETTINGS_NAME
              value: {{ .Values.app.container.env.settingsName | quote }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.app.container.env.djangoSettingsModule }}
            - name: DEFAULT_ORG_ID
              value: {{ .Values.app.container.env.defaultOrgId  }}
      
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
          args: ["--port=5432",
                    "-instances={{ .Values.app.container.env.db.instanceName }}",
                    "-credential_file={{ .Values.app.container.googleApplicationCredentialsSecret.filePath }}"]

          volumeMounts:
              - name: {{ .Values.app.container.googleApplicationCredentialsSecret.name }}
                mountPath: {{ .Values.app.container.googleApplicationCredentialsSecret.mountPath }}
                readOnly: true
      volumes:
          - name: {{ .Values.app.container.googleApplicationCredentialsSecret.name }}
            secret:
              secretName: {{ .Values.app.container.googleApplicationCredentialsSecret.name }}
