# Default values for mycarehub-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
    replicaCount: 1
    container:
        imagePullPolicy: "Always"
        port: 8080
        env:
            environment: "test"
        googleApplicationCredentialsSecret:
            name: "mycarehub-backend-service-account"
            filePath: "/secrets/gcp/key.json"
            mountPath: "/secrets/gcp"

service:
    type: NodePort
    port: 80


ingress:
  enabled: true
  className: "kong"
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "308"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []