# Generated by Django 3.2.11 on 2022-02-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='ages',
        ),
        migrations.AddField(
            model_name='community',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
