# Generated by Django 3.2.9 on 2022-03-23 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20220222_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='client_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PMTCT', 'PMTCT'), ('OTZ', 'OTZ'), ('OTZ_PLUS', 'OTZ Plus'), ('HVL', 'HVL'), ('OVC', 'OVC'), ('DREAMS', 'DREAMS'), ('HIGH_RISK', 'High Risk Clients'), ('SPOUSES', 'SPOUSES'), ('YOUTH', 'Youth'), ('KenyaEMR', 'Kenya EMR')], max_length=64), size=None),
        ),
    ]
