# Generated by Django 3.2.9 on 2022-04-01 14:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_client_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='gender',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=16), blank=True, help_text='The allowed gender(s) for users joining the community', null=True, size=None),
        ),
    ]
