# Generated by Django 3.2.14 on 2022-09-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_community_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postinghour',
            name='community',
        ),
        migrations.RemoveField(
            model_name='postinghour',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='PostingHour',
        ),
    ]
