# Generated by Django 3.2.9 on 2021-11-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211109_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flavour',
            field=models.CharField(choices=[('PRO', 'PRO'), ('CONSUMER', 'CONSUMER')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userpin',
            name='flavour',
            field=models.CharField(choices=[('PRO', 'PRO'), ('CONSUMER', 'CONSUMER')], max_length=32, null=True),
        ),
    ]
