# Generated by Django 3.2.9 on 2021-11-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpin',
            name='salt',
            field=models.TextField(null=True),
        ),
    ]
