# Generated by Django 3.2.9 on 2021-11-16 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userotp',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userotp',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
