# Generated by Django 3.2.9 on 2021-11-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211116_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='otp',
            field=models.CharField(default='', max_length=8),
        ),
    ]
