# Generated by Django 3.2.9 on 2021-11-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpin',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
