# Generated by Django 3.2.9 on 2022-01-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20211123_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofservice',
            name='flavour',
            field=models.CharField(choices=[('PRO', 'PRO'), ('CONSUMER', 'CONSUMER')], max_length=32, null=True),
        ),
    ]
