# Generated by Django 3.2.11 on 2022-03-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_termsofservice_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_security_count',
            field=models.IntegerField(default=0),
        ),
    ]
