# Generated by Django 3.2.11 on 2022-03-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_failed_security_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_update_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
