# Generated by Django 3.2.11 on 2022-04-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_set_nickname',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
