# Generated by Django 3.2.12 on 2022-03-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Identifier that is shared between KenyaEMR and MyCareHub', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('WAITING', 'Waiting'), ('MISSED', 'Missed'), ('COMPLETED', 'Completed'), ('INCONSULTATION', 'In Consultation'), ('WALKIN', 'Walk In'), ('CANCELLED', 'Cancelled'), ('NEEDSRESCHEDULE', 'Needs Reschedule')], max_length=36),
        ),
    ]
