# Generated by Django 3.2.12 on 2022-03-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20220215_1721'),
        ('appointments', '0002_auto_20220311_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.facility'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.CharField(blank=True, help_text='Individual conducting the appointment for when the staff is not in our system', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('RESCHEDULED', 'RESCHEDULED'), ('WAITING', 'WAITING'), ('MISSED', 'MISSED'), ('COMPLETED', 'COMPLETED'), ('IN_CONSULTATION', 'IN_CONSULTATION'), ('WALKIN', 'WALK IN'), ('CANCELLED', 'CANCELLED'), ('NEEDS_RESCHEDULE', 'NEEDS_RESCHEDULE')], max_length=36),
        ),
    ]
