# Generated by Django 3.2.11 on 2022-03-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20220314_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='has_rescheduled_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
