# Generated by Django 3.2.14 on 2022-09-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20220404_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
