# Generated by Django 3.2.16 on 2023-01-18 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import mycarehub.utils.general_utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfacilityallotment",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="organisation",
            field=models.ForeignKey(
                default=mycarehub.utils.general_utils.default_organisation,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="common_program_related",
                to="common.organisation",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="organisation",
            field=models.ForeignKey(
                default=mycarehub.utils.general_utils.default_organisation,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="common_facility_related",
                to="common.organisation",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="organisation",
            field=models.ForeignKey(
                default=mycarehub.utils.general_utils.default_organisation,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="common_auditlog_related",
                to="common.organisation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="program",
            unique_together={("name", "organisation")},
        ),
    ]
