# Generated by Django 3.2.9 on 2021-11-07 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfacilityallotment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilityattachment',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.facility'),
        ),
        migrations.AddField(
            model_name='facilityattachment',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_facilityattachment_related', to='common.organisation'),
        ),
        migrations.AddField(
            model_name='facility',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_facility_related', to='common.organisation'),
        ),
    ]
