# Generated by Django 3.2.16 on 2023-01-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="fhir_organization_id",
        ),
        migrations.AlterField(
            model_name="facility",
            name="county",
            field=models.CharField(
                blank=True,
                choices=[("Nairobi", "Nairobi"), ("Kajiado", "Kajiado")],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="mfl_code",
            field=models.IntegerField(blank=True, help_text="MFL Code", null=True, unique=True),
        ),
    ]
