# Generated by Django 3.2.9 on 2021-11-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20211110_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='cots',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='facility_owner',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='facility_type',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='facility_type_category',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='is_mycarehub_facility',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='keph_level',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='open_late_night',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='open_public_holidays',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='open_weekends',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='open_whole_day',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='operation_status',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='owner_type',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='public_visible',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='regulatory_body',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='sub_county',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='ward',
        ),
    ]
