# Generated by Django 3.2.9 on 2021-11-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20211115_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_id',
            new_name='user',
        ),
    ]
