# Generated by Django 4.2.6 on 2023-11-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_alter_auditlog_organisation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="email_address",
            field=models.EmailField(db_column="email_address", max_length=100),
        ),
        migrations.RenameField(
            model_name="organisation",
            old_name="email_address",
            new_name="email",
        ),
        migrations.AlterField(
            model_name="organisation",
            name="organisation_name",
            field=models.CharField(db_column="organisation_name", max_length=100, unique=True),
        ),
        migrations.RenameField(
            model_name="organisation",
            old_name="organisation_name",
            new_name="name",
        ),
    ]
