# Generated by Django 3.2.9 on 2021-11-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_rename_user_id_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='flavour',
            field=models.CharField(choices=[('PRO', 'PRO'), ('CONSUMER', 'CONSUMER')], max_length=32, null=True),
        ),
    ]
