# Generated by Django 3.2.9 on 2021-11-19 03:28

from django.db import migrations, models
import django.db.models.deletion
import mycarehub.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_contact_flavour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='deleted',
        ),
        migrations.AddField(
            model_name='organisation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='organisation',
            field=models.ForeignKey(default=mycarehub.users.models.default_organisation, on_delete=django.db.models.deletion.PROTECT, related_name='common_address_related', to='common.organisation'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='organisation',
            field=models.ForeignKey(default=mycarehub.users.models.default_organisation, on_delete=django.db.models.deletion.PROTECT, related_name='common_auditlog_related', to='common.organisation'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organisation',
            field=models.ForeignKey(default=mycarehub.users.models.default_organisation, on_delete=django.db.models.deletion.PROTECT, related_name='common_contact_related', to='common.organisation'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='organisation',
            field=models.ForeignKey(default=mycarehub.users.models.default_organisation, on_delete=django.db.models.deletion.PROTECT, related_name='common_facility_related', to='common.organisation'),
        ),
        migrations.AlterField(
            model_name='facilityattachment',
            name='organisation',
            field=models.ForeignKey(default=mycarehub.users.models.default_organisation, on_delete=django.db.models.deletion.PROTECT, related_name='common_facilityattachment_related', to='common.organisation'),
        ),
        migrations.AlterField(
            model_name='userfacilityallotment',
            name='organisation',
            field=models.ForeignKey(default=mycarehub.users.models.default_organisation, on_delete=django.db.models.deletion.PROTECT, related_name='common_userfacilityallotment_related', to='common.organisation'),
        ),
    ]
