# Generated by Django 3.2.9 on 2021-11-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20211123_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityattachment',
            name='content_type',
            field=models.CharField(choices=[('image/png', 'PNG'), ('image/jpeg', 'JPEG'), ('application/pdf', 'PDF'), ('application/vnd.ms-excel', 'xlsx'), ('application/msword', 'doc'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document.docx', 'docx'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'xlsx'), ('text/plain', 'text'), ('video/mp4', 'MP4 Video'), ('audio/mp4', 'MP4 Audio')], max_length=100),
        ),
    ]
