# Generated by Django 3.2.9 on 2021-11-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_facilityattachment_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
