# Generated by Django 3.2.12 on 2022-02-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_value',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('contact_value', 'flavour')},
        ),
    ]
