# Generated by Django 3.2.12 on 2022-03-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20220215_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='fhir_organization_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
