# Generated by Django 3.2.11 on 2022-05-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_usersurveys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersurveys',
            old_name='survey_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='usersurveys',
            old_name='survey_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='usersurveys',
            old_name='survey_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='usersurveys',
            name='form_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersurveys',
            name='link_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersurveys',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersurveys',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
