# Generated by Django 3.2.12 on 2022-06-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20220513_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='sub_county',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='county',
            field=models.CharField(blank=True, choices=[('Nairobi', 'Nairobi'), ('Kajiado', 'Kajiado')], max_length=64, null=True),
        ),
    ]
