# Generated by Django 3.2.13 on 2022-07-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
