# Generated by Django 3.2.12 on 2022-06-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_facility_sub_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.TextField(help_text='Facility Name', max_length=100),
        ),
    ]
