# Generated by Django 3.2.14 on 2022-09-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_feedback_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersurveys',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='usersurveys',
            name='user',
        ),
        migrations.DeleteModel(
            name='FacilityAttachment',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserSurveys',
        ),
    ]
