# Generated by Django 3.2.14 on 2022-09-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20220909_1417'),
        ('clients', '0035_auto_20220909_1417'),
        ('common', '0024_auto_20220906_1131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contact',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
