# Generated by Django 3.2.16 on 2023-01-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={},
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.TextField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('name', 'organisation')},
        ),
    ]
