# Generated by Django 3.2.14 on 2022-09-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeningtools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningtoolsresponse',
            name='client',
        ),
        migrations.RemoveField(
            model_name='screeningtoolsresponse',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='screeningtoolsresponse',
            name='question',
        ),
        migrations.DeleteModel(
            name='ScreeningToolsQuestion',
        ),
        migrations.DeleteModel(
            name='ScreeningToolsResponse',
        ),
    ]
