# Generated by Django 3.2.17 on 2023-02-14 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enrollment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
