# Generated by Django 4.1.9 on 2023-05-04 13:46

import django.db.models.deletion
from django.db import migrations, models

import mycarehub.utils.general_utils


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_alter_auditlog_organisation_and_more"),
        ("clients", "0003_client_enrollment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="organisation",
            field=models.ForeignKey(
                default=mycarehub.utils.general_utils.default_organisation,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="common.organisation",
            ),
        ),
    ]
