# Generated by Django 3.2.9 on 2021-11-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_auditlog_timestamp'),
        ('clients', '0004_auto_20211109_1345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientfacility',
            unique_together={('client', 'facility')},
        ),
    ]
