# Generated by Django 3.2.9 on 2021-11-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_clientfacility_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfacility',
            name='notes',
            field=models.TextField(default='-'),
        ),
    ]
