# Generated by Django 3.2.9 on 2021-11-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clientfacility_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientfacility',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identifier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatedperson',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityquestionresponse',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
