# Generated by Django 3.2.9 on 2021-11-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20211110_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityquestion',
            name='flavour',
            field=models.CharField(choices=[('PRO', 'PRO'), ('CONSUMER', 'CONSUMER')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='securityquestionresponse',
            name='flavour',
            field=models.CharField(choices=[('PRO', 'PRO'), ('CONSUMER', 'CONSUMER')], max_length=32, null=True),
        ),
    ]
