# Generated by Django 3.2.9 on 2021-11-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20211116_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityquestionresponse',
            name='flavour',
        ),
    ]
