# Generated by Django 3.2.9 on 2021-11-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20211119_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityquestionresponse',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
    ]
