# Generated by Django 3.2.9 on 2021-11-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_securityquestionresponse_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityquestion',
            name='flavour',
            field=models.CharField(blank=True, choices=[('PRO', 'PRO'), ('CONSUMER', 'CONSUMER')], max_length=32, null=True),
        ),
    ]
