# Generated by Django 3.2.9 on 2021-11-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_securityquestion_flavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='identifier_value',
            field=models.TextField(unique=True),
        ),
    ]
