# Generated by Django 3.2.9 on 2021-11-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_identifier_identifier_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='identifier_value',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='identifier',
            unique_together={('identifier_type', 'identifier_value')},
        ),
    ]
