# Generated by Django 3.2.9 on 2021-11-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdiaryquote',
            name='by',
            field=models.TextField(default='myCareHub Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthdiaryentry',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
