# Generated by Django 3.2.9 on 2022-01-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_auto_20220110_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='caregiver_type',
            field=models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SIBLING', 'Sibling'), ('HEALTHCARE_PROFESSIONAL', 'Healthcare Professional')], max_length=64),
        ),
    ]
