# Generated by Django 3.2.11 on 2022-02-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_alter_caregiver_caregiver_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='identifiers',
        ),
    ]
