# Generated by Django 3.2.9 on 2022-02-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_alter_caregiver_caregiver_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='in_progress_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='in_progress_by',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='resolved_by',
        ),
    ]
