# Generated by Django 3.2.9 on 2022-02-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_default_facility'),
        ('clients', '0019_alter_caregiver_caregiver_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='in_progress_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_request_in_progress_by_staff', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_request_resolved_by_staff', to='staff.staff'),
        ),
    ]
