# Generated by Django 3.2.11 on 2022-02-02 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_remove_client_identifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.identifier', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='identifiers',
            field=models.ManyToManyField(related_name='client_identifiers', through='clients.ClientIdentifier', to='clients.Identifier'),
        ),
    ]
