# Generated by Django 3.2.9 on 2022-02-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_servicerequest_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='facility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
