# Generated by Django 3.2.9 on 2022-02-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_faq'),
        ('clients', '0025_remove_servicerequest_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.facility'),
        ),
    ]
