# Generated by Django 3.2.12 on 2022-02-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_servicerequest_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('RED_FLAG', 'RED FLAG'), ('PIN_RESET', 'PIN_RESET'), ('PROFILE_UPDATE', 'PROFILE_UPDATE')], max_length=36),
        ),
    ]
