# Generated by Django 3.2.11 on 2022-03-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_servicerequest_ccc_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='ccc_number',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
