# Generated by Django 3.2.9 on 2022-04-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_alter_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedperson',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=16),
        ),
    ]
