# Generated by Django 3.2.11 on 2022-06-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_client_client_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityquestion',
            name='response_type',
            field=models.CharField(choices=[('TEXT', 'Text Response'), ('DATE', 'Date Response'), ('NUMBER', 'Number Response'), ('BOOLEAN', 'Boolean Response'), ('NUMBER_STRING', 'Number String Response')], max_length=32),
        ),
    ]
