# Generated by Django 3.2.14 on 2022-09-06 08:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20220906_1131'),
        ('clients', '0033_client_client_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdiaryentry',
            name='client',
        ),
        migrations.RemoveField(
            model_name='healthdiaryentry',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='healthdiaryquote',
            name='organisation',
        ),
        migrations.AlterUniqueTogether(
            name='identifier',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='relatedperson',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='relatedperson',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='relatedperson',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='securityquestion',
            name='organisation',
        ),
        migrations.AlterUniqueTogether(
            name='securityquestionresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='securityquestionresponse',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='securityquestionresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='securityquestionresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='in_progress_by',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='client',
            name='identifiers',
        ),
        migrations.RemoveField(
            model_name='client',
            name='related_persons',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
        migrations.DeleteModel(
            name='HealthDiaryAttachment',
        ),
        migrations.DeleteModel(
            name='HealthDiaryEntry',
        ),
        migrations.DeleteModel(
            name='HealthDiaryQuote',
        ),
        migrations.DeleteModel(
            name='Identifier',
        ),
        migrations.DeleteModel(
            name='RelatedPerson',
        ),
        migrations.DeleteModel(
            name='SecurityQuestion',
        ),
        migrations.DeleteModel(
            name='SecurityQuestionResponse',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
