# Generated by Django 3.2.16 on 2023-01-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_auto_20220909_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='caregiver',
        ),
        migrations.RemoveField(
            model_name='client',
            name='chv',
        ),
        migrations.RemoveField(
            model_name='client',
            name='current_facility',
        ),
        migrations.RemoveField(
            model_name='client',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='clientfacility',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clientfacility',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientfacility',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='clientfacility',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='Caregiver',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientFacility',
        ),
    ]
