# Generated by Django 3.2.16 on 2023-01-24 09:00

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20230124_1200'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='facilities',
            field=modelcluster.fields.ParentalManyToManyField(help_text='Determines which facilities content is meant for.', to='common.Facility'),
        ),
    ]
