# Generated by Django 3.2.9 on 2021-11-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('content', '0002_auto_20211119_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='An optional banner image. When present, it will be displayed above the content e.g above the article. This makes sense mostly for text articles.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_hero_image', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='contentitemcategory',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='An optional icon for the content item category. This will be shown in the user interface so it should be chosen with care.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_item_category_icons', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='contentitemdocumentlink',
            name='document',
            field=models.ForeignKey(help_text='Select or upload a PDF document. It is IMPORTANT to limit these documents to PDFs - otherwise the mobile app may not be able to display them properly.', on_delete=django.db.models.deletion.CASCADE, related_name='content_item_documents', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='contentitemgalleryimage',
            name='image',
            field=models.ForeignKey(help_text='Select or upload an image. Most of these images will be viewed on mobile devices. The ideal image should be large enough to render clearly on high end mobile devices but not so large that it costs a lot of bandwidth to download. One good size guideline to aim for is 800x1200 pixels. This is a guideline, not an iron-clad rule.', on_delete=django.db.models.deletion.PROTECT, related_name='content_item_gallery_images', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='contentitemmedialink',
            name='featured_media',
            field=models.ForeignKey(help_text='Select or upload an audio or video file. In order to maximize compatibility, please stick to common audio/video formats. For video, H264 encoded MP4 files are recommended. For audio, AAC (Advanced Audio Codec) files are recommended. ', on_delete=django.db.models.deletion.CASCADE, related_name='content_item_media', to='wagtailmedia.media'),
        ),
    ]
