# Generated by Django 3.2.14 on 2022-12-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_auto_20220909_1417'),
        ('content', '0003_auto_20211122_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_contentitem_related', to='common.organisation'),
        ),
        migrations.AddField(
            model_name='contentitemindexpage',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_contentitemindexpage_related', to='common.organisation'),
        ),
    ]
