# Generated by Django 3.2.9 on 2021-12-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20211122_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='item_type',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('AUDIO_VIDEO', 'Audio Video'), ('PDF_DOCUMENT', 'Pdf Document'), ('GALLERY', 'Gallery')], help_text='Whether this item is an article, audio/video or document. This is used by the mobile app to determine how to render content. e.g with an article, the layout will be hero_image > body while for audio-visual content the media will come first and the body last. For documents, the document(s) will also be presented before the body text.', max_length=64),
        ),
    ]
