# Generated by Django 3.2.16 on 2023-01-30 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_customimage_customrendition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ForeignKey(blank=True, help_text='An optional author picture (will be displayed publicly)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_image', to='content.customimage'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='An optional banner image. When present, it will be displayed above the content e.g above the article. This makes sense mostly for text articles.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_hero_image', to='content.customimage'),
        ),
        migrations.AlterField(
            model_name='contentitemcategory',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='An optional icon for the content item category. This will be shown in the user interface so it should be chosen with care.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_item_category_icons', to='content.customimage'),
        ),
        migrations.AlterField(
            model_name='contentitemgalleryimage',
            name='image',
            field=models.ForeignKey(help_text='Select or upload an image. Most of these images will be viewed on mobile devices. The ideal image should be large enough to render clearly on high end mobile devices but not so large that it costs a lot of bandwidth to download. One good size guideline to aim for is 800x1200 pixels. This is a guideline, not an iron-clad rule.', on_delete=django.db.models.deletion.PROTECT, related_name='content_item_gallery_images', to='content.customimage'),
        ),
    ]
