# Generated by Django 3.2.14 on 2022-12-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_auto_20220909_1417'),
        ('content', '0005_custommedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitemcategory',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_contentitemcategory_related', to='common.organisation'),
        ),
    ]
