# Generated by Django 3.2.16 on 2023-02-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20230131_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customimage',
            options={'permissions': [('choose_image', 'Can choose image')]},
        ),
    ]
