# Generated by Django 3.2.16 on 2023-01-06 18:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_program'),
        ('content', '0006_contentitemcategory_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='programs',
            field=modelcluster.fields.ParentalManyToManyField(to='common.Program'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_contentitem_related', to='common.program'),
        ),
        migrations.AddField(
            model_name='contentitemcategory',
            name='programs',
            field=modelcluster.fields.ParentalManyToManyField(to='common.Program'),
        ),
        migrations.AddField(
            model_name='contentitemindexpage',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_contentitemindexpage_related', to='common.program'),
        ),
    ]
