# Generated by Django 3.2.18 on 2023-03-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('common', '0006_auto_20230214_1434'),
        ('content', '0007_alter_customimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FafanukaContentItem',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(help_text='This will be shown to readers as the publication date', verbose_name='Post date')),
                ('category', models.CharField(choices=[('JUST_CURIOUS', 'Just Curious'), ('TYPE 1', 'Type 1'), ('TYPE 2', 'Type 2'), ('GESTATIONAL', 'Gestational')], max_length=64)),
                ('english_content', models.CharField(max_length=160)),
                ('kiswahili_content', models.CharField(max_length=160)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_fafanukacontentitem_related', to='common.organisation')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_fafanukacontentitem_related', to='common.program')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
