# Generated by Django 3.2.16 on 2023-01-10 09:00

from django.db import migrations, models
import django.db.models.deletion
import mycarehub.utils.general_utils


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_auto_20230110_1143'),
        ('content', '0007_auto_20230106_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitemindexpage',
            name='program',
            field=models.ForeignKey(blank=True, default=mycarehub.utils.general_utils.default_program, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_contentitemindexpage_related', to='common.program'),
        ),
    ]
