# Generated by Django 3.2.18 on 2023-03-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_fafanukacontentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fafanukacontentitem',
            name='category',
            field=models.CharField(choices=[('GENERAL DIABETES TIPS', 'General Diabetes Tips'), ('TYPE 1 DIABETES', 'Type 1 Diabetes'), ('TYPE 2 DIABETES', 'Type 2 Diabetes'), ('GESTATIONAL DIABETES', 'Gestational Diabetes')], max_length=64),
        ),
    ]
