# Generated by Django 3.2.18 on 2023-03-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_fafanukacontentitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fafanukacontentitem',
            name='english_content',
            field=models.TextField(max_length=160),
        ),
        migrations.AlterField(
            model_name='fafanukacontentitem',
            name='kiswahili_content',
            field=models.TextField(max_length=160),
        ),
    ]
