# Generated by Django 3.2.20 on 2023-09-12 07:35

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import mycarehub.common.models.base_models
import mycarehub.utils.general_utils


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_alter_auditlog_organisation_and_more"),
        ("content", "0009_smscontentitem_smsitemcategory_smsitemtag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smsitemtag",
            name="organisation",
        ),
        migrations.CreateModel(
            name="SMSContentItemTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "organisation",
                    models.ForeignKey(
                        default=mycarehub.utils.general_utils.default_organisation,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_smscontentitemtag_related",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            managers=[
                ("objects", mycarehub.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.CreateModel(
            name="SMSContentItemCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=64)),
                ("sequence_key", models.IntegerField(unique=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        default=mycarehub.utils.general_utils.default_organisation,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_smscontentitemcategory_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.program",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            managers=[
                ("objects", mycarehub.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AlterField(
            model_name="smscontentitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="content.smscontentitemcategory",
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitem",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tags",
                to="content.smscontentitemtag",
            ),
        ),
        migrations.DeleteModel(
            name="SMSItemCategory",
        ),
        migrations.DeleteModel(
            name="SMSItemTag",
        ),
    ]
