# Generated by Django 3.2.20 on 2023-09-12 13:27

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_alter_auditlog_organisation_and_more"),
        ("content", "0010_auto_20230912_1035"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smscontentitemcategory",
            options={"verbose_name_plural": "sms content item categories"},
        ),
        migrations.AlterModelOptions(
            name="smscontentitemtag",
            options={"verbose_name_plural": "sms content item tags"},
        ),
        migrations.AddField(
            model_name="smscontentitemcategory",
            name="programs",
            field=modelcluster.fields.ParentalManyToManyField(to="common.Program"),
        ),
        migrations.AddField(
            model_name="smscontentitemtag",
            name="programs",
            field=modelcluster.fields.ParentalManyToManyField(to="common.Program"),
        ),
        migrations.AlterUniqueTogether(
            name="smscontentitemcategory",
            unique_together={("sequence_key", "code")},
        ),
        migrations.RemoveField(
            model_name="smscontentitemcategory",
            name="program",
        ),
    ]
