# Generated by Django 3.2.18 on 2023-04-04 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mycarehub.common.models.base_models
import mycarehub.utils.general_utils
import uuid
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20230214_1434'),
        ('content', '0010_auto_20230328_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fafanukacontentitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fafanukacontentitem',
            name='english_content',
        ),
        migrations.RemoveField(
            model_name='fafanukacontentitem',
            name='kiswahili_content',
        ),
        migrations.AddField(
            model_name='fafanukacontentitem',
            name='sequence',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fafanukacontentitem',
            name='subgroup',
            field=models.CharField(choices=[(1, 'Diabetes General Information'), (2, 'Diabetes and Screening'), (3, 'Diabetes mangement'), (4, 'Diabetes and pregnancy'), (5, 'Exercise and diabetes'), (6, 'Diabetes and prevention'), (7, 'Diabetes and nutrition'), (8, 'Diabetes and complications'), (9, 'Diabetes and support'), (10, 'Diabetes and footcare')], default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='contentitemindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(default='Savannah', help_text="The content site's tagline"),
        ),
        migrations.AlterField(
            model_name='fafanukacontentitem',
            name='category',
            field=models.CharField(choices=[('001032833390', 'TYPE 1 DIABETES'), ('001032833389', 'TYPE 2 DIABETES'), ('001032833393', 'GESTATIONAL DIABETES'), ('001032833395', 'GENERAL')], default='001032833395', max_length=64),
        ),
        migrations.CreateModel(
            name='FafanukaContentBody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('KISWAHILI', 'Kiswahili')], max_length=255)),
                ('body', models.TextField(max_length=160)),
                ('organisation', models.ForeignKey(default=mycarehub.utils.general_utils.default_organisation, on_delete=django.db.models.deletion.PROTECT, related_name='content_fafanukacontentbody_related', to='common.organisation')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
            managers=[
                ('objects', mycarehub.common.models.base_models.AbstractBaseManager()),
            ],
        ),
        migrations.AddField(
            model_name='fafanukacontentitem',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_fafanukacontentitem_related', to='content.fafanukacontentbody'),
        ),
    ]
