# Generated by Django 3.2.18 on 2023-04-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20230404_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fafanukacontentitem',
            name='content',
        ),
        migrations.AddField(
            model_name='fafanukacontentitem',
            name='english_content',
            field=models.TextField(default='Hello World', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fafanukacontentitem',
            name='swahili_content',
            field=models.TextField(default='Habari Dunia', max_length=160),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FafanukaContentBody',
        ),
    ]
