# Generated by Django 3.2.20 on 2023-09-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_auto_20230912_1627"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smscontentitemcategory",
            name="sequence_key",
            field=models.IntegerField(),
        ),
    ]
