# Generated by Django 3.2.18 on 2023-04-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20230404_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fafanukacontentitem',
            name='subgroup',
            field=models.IntegerField(choices=[(1, 'Diabetes General Information'), (2, 'Diabetes and Screening'), (3, 'Diabetes mangement'), (4, 'Diabetes and pregnancy'), (5, 'Exercise and diabetes'), (6, 'Diabetes and prevention'), (7, 'Diabetes and nutrition'), (8, 'Diabetes and complications'), (9, 'Diabetes and support'), (10, 'Diabetes and footcare')], default=1),
        ),
    ]
