# Generated by Django 3.2.18 on 2023-04-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_fafanukacontentitem_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='fafanukacontentitem',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
