# Generated by Django 3.2.18 on 2023-04-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_fafanukacontentitem_sequence_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fafanukacontentitem',
            old_name='category',
            new_name='offer',
        ),
    ]
