# Generated by Django 3.2.20 on 2023-10-02 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_alter_auditlog_organisation_and_more"),
        ("content", "0014_alter_smscontentitemcategory_code"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="smscontentitemcategory",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="smscontentitemtag",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="smscontentitemcategory",
            name="active",
        ),
        migrations.RemoveField(
            model_name="smscontentitemcategory",
            name="created",
        ),
        migrations.RemoveField(
            model_name="smscontentitemcategory",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="smscontentitemcategory",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="smscontentitemcategory",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="smscontentitemcategory",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="smscontentitemtag",
            name="active",
        ),
        migrations.RemoveField(
            model_name="smscontentitemtag",
            name="created",
        ),
        migrations.RemoveField(
            model_name="smscontentitemtag",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="smscontentitemtag",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="smscontentitemtag",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="smscontentitemtag",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="smscontentitemcategory",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_smscontentitemcategory_related",
                to="common.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitemtag",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_smscontentitemtag_related",
                to="common.organisation",
            ),
        ),
    ]
