# Generated by Django 3.2.20 on 2023-10-03 13:02

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_alter_auditlog_organisation_and_more"),
        ("content", "0015_auto_20231002_1258"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smscontentitem",
            name="english_content",
        ),
        migrations.RemoveField(
            model_name="smscontentitem",
            name="swahili_content",
        ),
        migrations.AddField(
            model_name="smscontentitem",
            name="content",
            field=models.TextField(
                default="body",
                help_text="Write out the body of the content to be sent to subscribers",
                max_length=160,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="smscontentitem",
            name="category",
            field=models.ForeignKey(
                help_text="Category to associate content with",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="content.smscontentitemcategory",
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitem",
            name="tag",
            field=models.ForeignKey(
                help_text="Tag to associate content with",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tags",
                to="content.smscontentitemtag",
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitemcategory",
            name="code",
            field=models.CharField(
                help_text="A code that will be used to uniquely identify a category",
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitemcategory",
            name="name",
            field=models.CharField(
                help_text="This name will be displayed while creating sms content", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitemcategory",
            name="programs",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text="Select a program to assign this category", to="common.Program"
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitemcategory",
            name="sequence_key",
            field=models.IntegerField(
                help_text="A pre-determined value to be used while sequencing content under this category"
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitemtag",
            name="code",
            field=models.IntegerField(
                help_text="A pre-determined value that will be used to uniquely identify a tag"
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitemtag",
            name="name",
            field=models.CharField(
                help_text="This name will be displayed when creating sms content", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitemtag",
            name="programs",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text="Select a program to assign this tag", to="common.Program"
            ),
        ),
    ]
