# Generated by Django 3.2.20 on 2023-10-05 12:28

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_alter_auditlog_organisation_and_more"),
        ("content", "0016_auto_20231003_1602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentitem",
            name="facilities",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Determines which facilities content is meant for.",
                null=True,
                to="common.Facility",
            ),
        ),
    ]
