# Generated by Django 3.2.20 on 2023-10-25 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0017_alter_contentitem_facilities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="smscontentitem",
            old_name="content",
            new_name="body",
        ),
    ]
