# Generated by Django 4.2.6 on 2023-10-31 17:38

import django.db.models.deletion
import modelcluster.fields
import wagtail.images.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_alter_auditlog_organisation_and_more"),
        ("content", "0018_rename_content_smscontentitem_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentitem",
            name="facilities",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Determines which facilities content is meant for.",
                to="common.facility",
            ),
        ),
        migrations.AlterField(
            model_name="customrendition",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field="width",
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitem",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="common.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitem",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="common.program",
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitemcategory",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="common.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="smscontentitemtag",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="common.organisation",
            ),
        ),
    ]
