# Generated by Django 3.2.9 on 2022-01-25 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_faq'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='default_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_staff', to='common.facility'),
        ),
    ]
