# Generated by Django 3.2.11 on 2022-03-25 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20220215_1721'),
        ('staff', '0004_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_facility', to='common.facility'),
        ),
    ]
