# Generated by Django 3.2.14 on 2022-09-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_servicerequest_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='identifiers',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
