# Generated by Django 3.2.14 on 2022-09-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20220906_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='contacts',
        ),
    ]
