# Generated by Django 3.2.16 on 2023-01-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20220909_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
