# Generated by Django 3.2.14 on 2022-09-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorityrole',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='authorityrole',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='authorityrole',
            name='users',
        ),
        migrations.DeleteModel(
            name='AuthorityPermission',
        ),
        migrations.DeleteModel(
            name='AuthorityRole',
        ),
    ]
